version: '3.3'
services:
  node:
    container_name: NodeJS
    image: caffeineexpress:latest
    restart: always
    environment:
      - HOST=0.0.0.0
      - BD_NAME=express-ts
      - MONGO_URI=mongodb://mongodb-app:27017/express-ts
    ports:
      - 3000:3000
      - 8080:8080
    depends_on:
      - mongodb-app
    networks:
      - net
  mongodb-app:
    container_name: MongoDB
    image: mongo:5.0.3
    restart: always
    volumes:
      - ~/.docker-config/MongoDB:/data/db
      - ~/.docker-config/MongoDB:/data/configdb
    ports:
      - 27017:27017
    networks:
      - net
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: username
    #   MONGO_INITDB_ROOT_PASSWORD: example
networks:
  net:
    driver: bridge
